use std::collections::BTreeMap;
use std::path::Path;

use ts_rs::{Config, TS, TypeVisitor};

use crate::Method;

/// Generates every binding in memory and returns `(file name, contents)` pairs. 64-bit integers
/// are a `tsc` error (`LARGE_INT_NOT_ALLOWED` is deliberately undefined): JSON numbers are doubles,
/// so such a field would lose precision silently.
pub fn generate_bindings() -> BTreeMap<String, String> {
    let cfg = Config::new().with_large_int("LARGE_INT_NOT_ALLOWED");
    crate::collect_bindings(&cfg)
}

pub(crate) struct Collector<'a> {
    cfg: &'a Config,
    files: BTreeMap<String, String>,
}

impl<'a> Collector<'a> {
    pub fn new(cfg: &'a Config) -> Self {
        Self {
            cfg,
            files: BTreeMap::new(),
        }
    }

    pub fn add<T: TS + 'static + ?Sized>(&mut self) {
        self.visit::<T>();
    }

    /// `entries` are `(Methods line, names to import)` from `methods_entry`.
    pub fn finish(mut self, entries: Vec<(String, Vec<String>)>) -> BTreeMap<String, String> {
        let mut used: Vec<&String> = entries.iter().flat_map(|(_, names)| names).collect();
        used.sort();
        used.dedup();
        let mut text =
            String::from("// This file is generated by `cargo xtask bindings`. Do not edit it.\n");
        for name in used {
            text.push_str(&format!("import type {{ {name} }} from \"./{name}\";\n"));
        }
        text.push_str("\nexport type Methods = {\n");
        for (entry, _) in entries {
            text.push_str(&entry);
        }
        text.push_str("};\n");
        self.files.insert("Methods.ts".to_owned(), text);
        self.files
    }
}

impl TypeVisitor for Collector<'_> {
    fn visit<T: TS + 'static + ?Sized>(&mut self) {
        let Some(path) = T::output_path() else { return };
        let file = file_name(&path);
        if self.files.contains_key(&file) {
            return;
        }
        let text = T::export_to_string(self.cfg).expect("API type must be exportable");
        self.files.insert(file, text);
        T::visit_dependencies(self);
    }
}

fn file_name(path: &Path) -> String {
    path.file_name()
        .expect("output path has a file name")
        .to_string_lossy()
        .into_owned()
}

/// The `Methods` line for `M` (`()` is `null`), and the type names it needs imported.
pub(crate) fn methods_entry<M: Method>(cfg: &Config) -> (String, Vec<String>) {
    let (input, output) = (<M::Input as TS>::name(cfg), <M::Output as TS>::name(cfg));
    let imports = [
        (<M::Input as TS>::output_path(), &input),
        (<M::Output as TS>::output_path(), &output),
    ]
    .into_iter()
    .filter_map(|(path, name)| path.map(|_| name.clone()))
    .collect();
    (
        format!(
            "  {}: {{ input: {input}; output: {output}; bytesIn: {}; bytesOut: {} }};\n",
            M::NAME,
            M::ATTACHMENT_IN,
            M::ATTACHMENT_OUT,
        ),
        imports,
    )
}

#[cfg(test)]
mod tests {
    use std::path::PathBuf;

    use super::*;

    const STALE: &str = "TypeScript bindings are stale: run `cargo xtask bindings`";

    fn bindings_dir() -> PathBuf {
        Path::new(env!("CARGO_MANIFEST_DIR")).join("../../packages/core-client/src/generated")
    }

    /// Compares the generated bindings with the committed files. With `FC_UPDATE_BINDINGS=1` it
    /// rewrites them instead (that is what `cargo xtask bindings` does).
    #[test]
    fn committed_bindings_are_current() {
        let dir = bindings_dir();
        let generated = generate_bindings();
        if std::env::var("FC_UPDATE_BINDINGS").as_deref() == Ok("1") {
            let _ = std::fs::remove_dir_all(&dir);
            std::fs::create_dir_all(&dir).unwrap();
            for (name, text) in &generated {
                std::fs::write(dir.join(name), text).unwrap();
            }
            return;
        }
        let mut on_disk: Vec<String> = std::fs::read_dir(&dir)
            .unwrap_or_else(|_| panic!("{STALE}"))
            .map(|e| e.unwrap().file_name().to_string_lossy().into_owned())
            .collect();
        on_disk.sort();
        let expected: Vec<&String> = generated.keys().collect();
        assert!(on_disk.iter().eq(expected), "{STALE}");
        for (name, text) in &generated {
            let current = std::fs::read_to_string(dir.join(name)).unwrap();
            assert!(normalise(&current) == normalise(text), "{STALE} ({name})");
        }
    }

    /// Biome reformats the committed files (spacing, trailing commas, semicolons, a leading union bar, and it unquotes
    /// object keys), so compare without them. Quotes are ignored everywhere, which still catches
    /// any change to a name or a literal's text.
    fn normalise(s: &str) -> String {
        s.chars()
            .filter(|c| !c.is_whitespace() && !matches!(c, ',' | ';' | '"' | '|'))
            .collect()
    }
}
